# **Tugas 2 - Diskritisasi**

1. Carilah data yang bertipe numerik ( data klassifikasi)
2. Lakukan proses diskritisasi dengan *equal width* dan *equal frequency*
3. Lakukan proses diskritisasi dengan basis *entropy*
4. Kumpulkan tugas dengan link github ( web statis dari jupyter book)

### **Membaca data url**

In [1]:
import math
from math import log2
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None 
url = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
dataset_iris = pd.read_csv(url)
dataset_iris

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

### **1. Distraksi dengan equal width dan equal frequency**
**Distraksi** merupakan transformasi kolom menjadi type data lain. Tujuannya untuk membuat data menjadi lebih optimal yang nantinya memudahkan untuk di analisis


### **1.1 Equal Width**


Equal-width intervals adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar.

Menggunakan K = 3

Membuat kategori

In [2]:
#mengambil sampel data
sepal_length_eqW  = dataset_iris[["sepal.length"]]
sepal_width_eqW   = dataset_iris[["sepal.width"]]
petal_length_eqW  = dataset_iris[["petal.length"]]
petal_width_eqW   = dataset_iris[["petal.width"]]

In [3]:
#memisahkan tiap kolom
sepal_length_eqW["category"] = pd.cut(dataset_iris["sepal.length"],3, labels = ['kecil','sedang','besar'])
petal_length_eqW['category'] = pd.cut(dataset_iris["petal.length"],3, labels = ['kecil', 'sedang','besar'])
sepal_width_eqW['category'] = pd.cut(dataset_iris["sepal.width"],3, labels = ['kecil', 'sedang','besar'])
petal_width_eqW['category'] = pd.cut(dataset_iris["petal.width"],3, labels = ['kecil', 'sedang','besar'])

display(sepal_length_eqW)
display (petal_length_eqW)
display (sepal_width_eqW)
display (petal_width_eqW)

     sepal.length category
0             5.1    kecil
1             4.9    kecil
2             4.7    kecil
3             4.6    kecil
4             5.0    kecil
..            ...      ...
145           6.7   sedang
146           6.3   sedang
147           6.5   sedang
148           6.2   sedang
149           5.9   sedang

[150 rows x 2 columns]

     petal.length category
0             1.4    kecil
1             1.4    kecil
2             1.3    kecil
3             1.5    kecil
4             1.4    kecil
..            ...      ...
145           5.2    besar
146           5.0    besar
147           5.2    besar
148           5.4    besar
149           5.1    besar

[150 rows x 2 columns]

     sepal.width category
0            3.5   sedang
1            3.0   sedang
2            3.2   sedang
3            3.1   sedang
4            3.6   sedang
..           ...      ...
145          3.0   sedang
146          2.5    kecil
147          3.0   sedang
148          3.4   sedang
149          3.0   sedang

[150 rows x 2 columns]

     petal.width category
0            0.2    kecil
1            0.2    kecil
2            0.2    kecil
3            0.2    kecil
4            0.2    kecil
..           ...      ...
145          2.3    besar
146          1.9    besar
147          2.0    besar
148          2.3    besar
149          1.8    besar

[150 rows x 2 columns]

In [4]:
equalWidth = pd.DataFrame([])
equalWidth["sepal.length"] = dataset_iris["sepal.length"]
equalWidth['SL.category'] = sepal_length_eqW["category"]

equalWidth["petal.length"] = dataset_iris["petal.length"]
equalWidth["PL.category"] = petal_length_eqW["category"]

equalWidth["sepal.width"] = dataset_iris["sepal.width"]
equalWidth["SW.category"] = sepal_width_eqW["category"]

equalWidth["petal.width"] = dataset_iris["petal.width"]
equalWidth["PW.category"] = petal_width_eqW["category"]

equalWidth["variety"] = dataset_iris[["variety"]]

equalWidth

,sepal.length,SL.category,petal.length,PL.category,sepal.width,SW.category,petal.width,PW.category,variety
0,5.1,kecil,1.4,kecil,3.5,sedang,0.2,kecil,Setosa
1,4.9,kecil,1.4,kecil,3.0,sedang,0.2,kecil,Setosa
2,4.7,kecil,1.3,kecil,3.2,sedang,0.2,kecil,Setosa
3,4.6,kecil,1.5,kecil,3.1,sedang,0.2,kecil,Setosa
4,5.0,kecil,1.4,kecil,3.6,sedang,0.2,kecil,Setosa
...,...,...,...,...,...,...,...,...,...
145,6.7,sedang,5.2,besar,3.0,sedang,2.3,besar,Virginica
146,6.3,sedang,5.0,besar,2.5,kecil,1.9,besar,Virginica
147,6.5,sedang,5.2,besar,3.0,sedang,2.0,besar,Virginica
148,6.2,sedang,5.4,besar,3.4,sedang,2.3,besar,Virginica
149,5.9,sedang,5.1,besar,3.0,sedang,1.8,besar,Virginica

### **1.2 Equal Frequency**
Equal-frequency intervals adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar.

memisahkan tiap kolom yang akan dikonversi dari data tipe numerik ke tipe kategori

In [5]:
#mengambil sampel data
sepal_length_Freq  = dataset_iris[["sepal.length"]]
sepal_width_Freq   = dataset_iris[["sepal.width"]]
petal_length_Freq  = dataset_iris[["petal.length"]]
petal_width_Freq   = dataset_iris[["petal.width"]]

In [6]:
#memisahkan tiap kolom
sepal_length_Freq["category"] = pd.qcut(dataset_iris["sepal.length"],3, labels = ['kecil','sedang','besar'])
petal_length_Freq['category'] = pd.qcut(dataset_iris["petal.length"],3, labels = ['kecil', 'sedang','besar'])
sepal_width_Freq['category'] = pd.qcut(dataset_iris["sepal.width"],3, labels = ['kecil', 'sedang','besar'])
petal_width_Freq['category'] = pd.qcut(dataset_iris["petal.width"],3, labels = ['kecil', 'sedang','besar'])

display(sepal_length_Freq)
display (petal_length_Freq)
display (sepal_width_Freq)
display (petal_width_Freq)

     sepal.length category
0             5.1    kecil
1             4.9    kecil
2             4.7    kecil
3             4.6    kecil
4             5.0    kecil
..            ...      ...
145           6.7    besar
146           6.3   sedang
147           6.5    besar
148           6.2   sedang
149           5.9   sedang

[150 rows x 2 columns]

     petal.length category
0             1.4    kecil
1             1.4    kecil
2             1.3    kecil
3             1.5    kecil
4             1.4    kecil
..            ...      ...
145           5.2    besar
146           5.0    besar
147           5.2    besar
148           5.4    besar
149           5.1    besar

[150 rows x 2 columns]

     sepal.width category
0            3.5    besar
1            3.0   sedang
2            3.2   sedang
3            3.1   sedang
4            3.6    besar
..           ...      ...
145          3.0   sedang
146          2.5    kecil
147          3.0   sedang
148          3.4    besar
149          3.0   sedang

[150 rows x 2 columns]

     petal.width category
0            0.2    kecil
1            0.2    kecil
2            0.2    kecil
3            0.2    kecil
4            0.2    kecil
..           ...      ...
145          2.3    besar
146          1.9    besar
147          2.0    besar
148          2.3    besar
149          1.8    besar

[150 rows x 2 columns]

menggabungkan hasil equal frequency

In [7]:
equalFreq = pd.DataFrame([])
equalFreq["sepal.length"] = dataset_iris["sepal.length"]
equalFreq['SL.category'] = sepal_length_Freq["category"]

equalFreq["petal.length"] = dataset_iris["petal.length"]
equalFreq["PL.category"] = petal_length_Freq["category"]

equalFreq["sepal.width"] = dataset_iris["sepal.width"]
equalFreq["SW.category"] = sepal_width_Freq["category"]

equalFreq["petal.width"] = dataset_iris["petal.width"]
equalFreq["PW.category"] = petal_width_Freq["category"]

equalFreq["variety"] = dataset_iris[["variety"]]

equalFreq

,sepal.length,SL.category,petal.length,PL.category,sepal.width,SW.category,petal.width,PW.category,variety
0,5.1,kecil,1.4,kecil,3.5,besar,0.2,kecil,Setosa
1,4.9,kecil,1.4,kecil,3.0,sedang,0.2,kecil,Setosa
2,4.7,kecil,1.3,kecil,3.2,sedang,0.2,kecil,Setosa
3,4.6,kecil,1.5,kecil,3.1,sedang,0.2,kecil,Setosa
4,5.0,kecil,1.4,kecil,3.6,besar,0.2,kecil,Setosa
...,...,...,...,...,...,...,...,...,...
145,6.7,besar,5.2,besar,3.0,sedang,2.3,besar,Virginica
146,6.3,sedang,5.0,besar,2.5,kecil,1.9,besar,Virginica
147,6.5,besar,5.2,besar,3.0,sedang,2.0,besar,Virginica
148,6.2,sedang,5.4,besar,3.4,besar,2.3,besar,Virginica
149,5.9,sedang,5.1,besar,3.0,sedang,1.8,besar,Virginica

menggabungkan hasil equal widht dengan equal frequency

In [8]:
combine = pd.DataFrame([])
combine['sepal.length'] = dataset_iris["sepal.length"]
combine['SL.EWidth'] = sepal_length_eqW["category"]
combine['SL.EFreq'] = sepal_length_Freq["category"]

combine['petal.length'] = dataset_iris["petal.length"]
combine['PL.EWidth'] = petal_length_eqW["category"]
combine['PL.EFreq'] = petal_length_Freq["category"]

combine['sepal.width'] = dataset_iris["sepal.width"]
combine['SW.EWidth'] = sepal_width_eqW["category"]
combine['SW.EFreq'] = sepal_width_Freq["category"]

combine['petal.width'] = dataset_iris["petal.width"]
combine['PW.EWidth'] = petal_width_eqW["category"]
combine['PW.EFreq'] = petal_width_Freq["category"]

combine["variety"] = dataset_iris[["variety"]]

combine

,sepal.length,SL.EWidth,SL.EFreq,petal.length,PL.EWidth,PL.EFreq,sepal.width,SW.EWidth,SW.EFreq,petal.width,PW.EWidth,PW.EFreq,variety
0,5.1,kecil,kecil,1.4,kecil,kecil,3.5,sedang,besar,0.2,kecil,kecil,Setosa
1,4.9,kecil,kecil,1.4,kecil,kecil,3.0,sedang,sedang,0.2,kecil,kecil,Setosa
2,4.7,kecil,kecil,1.3,kecil,kecil,3.2,sedang,sedang,0.2,kecil,kecil,Setosa
3,4.6,kecil,kecil,1.5,kecil,kecil,3.1,sedang,sedang,0.2,kecil,kecil,Setosa
4,5.0,kecil,kecil,1.4,kecil,kecil,3.6,sedang,besar,0.2,kecil,kecil,Setosa
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,6.7,sedang,besar,5.2,besar,besar,3.0,sedang,sedang,2.3,besar,besar,Virginica
146,6.3,sedang,sedang,5.0,besar,besar,2.5,kecil,kecil,1.9,besar,besar,Virginica
147,6.5,sedang,besar,5.2,besar,besar,3.0,sedang,sedang,2.0,besar,besar,Virginica
148,6.2,sedang,sedang,5.4,besar,besar,3.4,sedang,besar,2.3,besar,besar,Virginica
149,5.9,sedang,sedang,5.1,besar,besar,3.0,sedang,sedang,1.8,besar,besar,Virginica

### **2. Entrophy**

**Diskritisasi berbasis entropi** (entropy based discretization) adalah salah satu jenis algoritma diskritisasi terawasi yang menggunakan mekanisme top- down. Tujuan dari algoritma ini adalah mendapatkan partisi yang mengandung baris data dari kelas yang sama sebanyak mungkin.  
Rumus Entrophy:  
![image.png](https://cdn.mathpix.com/snip/images/T3MAnkOgvu54ASi68sQ5fR96rPCLPxjYofOqC9L4IpM.original.fullsize.png)

In [9]:
#labels

labels = ['kecil','sedang','besar']

In [13]:
#menambah sample data
sample = combine[['sepal.length','SL.EWidth']]
sample.describe()

       sepal.length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

fungsi menghitung banyakanya data berdasarkan kategori

In [14]:
np.random.seed(0)
sample["categori"] = np.where(np.random.choice(2,sample.shape[0]) < 1,"kecil","sedang")
sample

     sepal.length SL.EWidth categori
0             5.1     kecil    kecil
1             4.9     kecil   sedang
2             4.7     kecil   sedang
3             4.6     kecil    kecil
4             5.0     kecil   sedang
..            ...       ...      ...
145           6.7    sedang    kecil
146           6.3    sedang   sedang
147           6.5    sedang   sedang
148           6.2    sedang   sedang
149           5.9    sedang   sedang

[150 rows x 3 columns]

Membuat fungsi GetOverollCategory (keseluruhan) yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [15]:
def overalCategory(sample, labels, col, category):
  group = sample.groupby(category).count()
  return [group.loc[label, col] for label in labels]

fungsi untuk prosses info D

In [16]:
def split(nilai, sample, labels, col, category):
  less_group = sample[sample[col] < nilai]
  greater_group = sample[sample[col] >= nilai]

  length_less_group = overalCategory(less_group, labels, col, category)
  length_greater_group = overalCategory(greater_group, labels, col, category)

  return (length_less_group, length_greater_group)

Membuat fungsi entropy untuk melakukan perhitungan entropy

In [17]:
def entropy(d):
  return -(sum([i/sum(d) * log2(i/sum(d)) if i/sum(d) != 0 else 0 for i in d]))

Membuat fungsi info dan gain

In [18]:
def info(d, sample):
  return sum([(sum(i) / sample.shape[0]) * entropy(i) for i in d])

### **2.1 Gain**
<p align="justify">
Setelah membagi dataset berdasarkan sebuah atribut kedalam subset yang lebih kecil, entropi dari data tersebut akan berubah. Perubahan entropi ini dapat digunakan untuk menentukan bagus tidaknya pembagian data yang telah dilakukan. Perubahan entropi ini disebut dengan information gain dalam Algoritme C4.5. Information gain ini diukur dengan menghitung selisih antara entropi dataset sebelum dan sesudah pembagian (splitting) dilakukan. Pembagian yang terbaik
akan menghasilkan entropi subset yang paling kecil, dengan demikian berdampak pada information gain yang terbesar. 
</p>

$$
\begin{align*}
\displaystyle 𝐺𝑎𝑖𝑛(𝐴) &= 𝐸𝑛𝑡𝑟𝑜𝑝𝑖(𝑆) − \sum_{i=1}^{k}\frac{\left| S \right|}{\left| S_{i} \right|} * 𝐸𝑛𝑡𝑟𝑜𝑝𝑖(𝑆_{i}) \\
Keterangan &: \\
𝑆 &: himpunan \ kasus \\
𝐴 &: atribut \\
k &: jumlah \ partisi \ atribut \ A \\
|𝑆𝑖| &: jumlah \ kasus \ pada \ partisi \ ke-i \\
|𝑆| &: jumlah \ kasus \ dalam \ S 
\end{align*}
$$

menghitung nilai gain

In [19]:
def gain(inisial, new):
  return inisial - new

menghitung nilai entrophy overall

In [21]:
d = overalCategory(sample, labels, 'sepal.length', 'SL.EWidth')
Einisial = entropy(d)
Einisial

1.4278417085296922

In [22]:
#mencari  split 4.5
az = split(4.5, sample, labels, 'sepal.length', 'SL.EWidth')
Enew1 = info(az, sample)
gain(Einisial, Enew1)

0.03671508206271512

In [23]:
#mencari split 5.5
az = split(5.5, sample, labels, 'sepal.length', 'SL.EWidth')
Enew2 = info(az, sample)
gain(Einisial, Enew2)

0.7243785559543089

In [24]:
#mencari split 6.5
az = split(6.5, sample, labels, 'sepal.length', 'SL.EWidth')
Enew3 = info(az, sample)
gain(Einisial, Enew3)

0.43166487471484216

**Kesimpulan**

semakin kecil nilai gain terhadapa einsial dan enew, makan semakin bagus akurasinya